-- Migration: Seed Exercise Data

-- 1. Seeds for exercises table
INSERT INTO public.exercises (legacy_id, name, muscle_groups, category, equipment, default_sets, default_reps, duration)
VALUES
  ('ex-push-ups', 'Push-ups', '{"chest","shoulders"}', 'compound', '{"bodyweight"}', 3, '10-15', NULL),
  ('ex-db-bench-press', 'Dumbbell Bench Press', '{"chest"}', 'compound', '{"dumbbell"}', 3, '8-12', NULL),
  ('ex-bb-bench-press', 'Barbell Bench Press', '{"chest"}', 'compound', '{"barbell"}', 3, '6-10', NULL),
  ('ex-inc-db-press', 'Incline Dumbbell Press', '{"chest"}', 'accessory', '{"dumbbell"}', 3, '10-12', NULL),
  ('ex-mach-chest-press', 'Machine Chest Press', '{"chest"}', 'compound', '{"machine"}', 3, '10-12', NULL),
  ('ex-db-flyes', 'Dumbbell Flyes', '{"chest"}', 'isolation', '{"dumbbell"}', 3, '12-15', NULL),
  ('ex-cable-cross', 'Cable Crossovers', '{"chest"}', 'isolation', '{"cable"}', 3, '12-15', NULL),
  ('ex-band-chest-press', 'Resistance Band Chest Press', '{"chest"}', 'compound', '{"band"}', 3, '15-20', NULL),
  ('ex-arm-circles', 'Arm Circles', '{"chest","shoulders","mobility"}', 'warmup', '{"bodyweight"}', NULL, NULL, '2 min'),
  ('ex-pull-ups', 'Pull-ups', '{"back","arms"}', 'compound', '{"bodyweight"}', 3, '5-10', NULL),
  ('ex-lat-pulldown', 'Lat Pulldown', '{"back"}', 'compound', '{"machine","cable"}', 3, '10-12', NULL),
  ('ex-bb-row', 'Barbell Row', '{"back"}', 'compound', '{"barbell"}', 3, '8-10', NULL),
  ('ex-db-row', 'Dumbbell Row', '{"back"}', 'accessory', '{"dumbbell"}', 3, '10-12', NULL),
  ('ex-seated-cable-row', 'Seated Cable Row', '{"back"}', 'accessory', '{"cable","machine"}', 3, '10-12', NULL),
  ('ex-straight-arm-pulldown', 'Straight Arm Pulldown', '{"back"}', 'isolation', '{"cable","band"}', 3, '12-15', NULL),
  ('ex-superman-hold', 'Superman Hold', '{"back","core"}', 'isolation', '{"bodyweight"}', 3, NULL, '30s'),
  ('ex-inverted-rows', 'Inverted Rows (Table)', '{"back"}', 'compound', '{"bodyweight"}', 3, '10-12', NULL),
  ('ex-cat-cow', 'Cat-Cow Stretch', '{"back","mobility"}', 'warmup', '{"bodyweight"}', NULL, NULL, '1 min'),
  ('ex-overhead-press', 'Overhead Press', '{"shoulders"}', 'compound', '{"barbell","dumbbell"}', 3, '8-10', NULL),
  ('ex-pike-pushups', 'Pike Push-ups', '{"shoulders"}', 'compound', '{"bodyweight"}', 3, '8-12', NULL),
  ('ex-lateral-raise', 'Lateral Raise', '{"shoulders"}', 'isolation', '{"dumbbell","cable","band"}', 3, '12-15', NULL),
  ('ex-front-raise', 'Front Raise', '{"shoulders"}', 'isolation', '{"dumbbell","band"}', 3, '12-15', NULL),
  ('ex-face-pulls', 'Face Pulls', '{"shoulders","back"}', 'accessory', '{"cable","band"}', 3, '15-20', NULL),
  ('ex-mach-shoulder-press', 'Machine Shoulder Press', '{"shoulders"}', 'compound', '{"machine"}', 3, '10-12', NULL),
  ('ex-shoulder-dislocations', 'Shoulder Dislocations (Broomstick)', '{"shoulders","mobility"}', 'warmup', '{"bodyweight"}', NULL, NULL, '2 min'),
  ('ex-bb-squat', 'Barbell Squat', '{"legs"}', 'compound', '{"barbell"}', 3, '6-10', NULL),
  ('ex-goblet-squat', 'Goblet Squat', '{"legs","core"}', 'compound', '{"dumbbell"}', 3, '10-12', NULL),
  ('ex-bodyweight-squat', 'Bodyweight Squats', '{"legs"}', 'compound', '{"bodyweight"}', 3, '15-20', NULL),
  ('ex-leg-press', 'Leg Press', '{"legs"}', 'compound', '{"machine"}', 3, '10-12', NULL),
  ('ex-rdl', 'Romanian Deadlift', '{"legs","back"}', 'compound', '{"barbell","dumbbell"}', 3, '8-12', NULL),
  ('ex-lunges', 'Lunges', '{"legs"}', 'accessory', '{"bodyweight","dumbbell"}', 3, '10-12 each', NULL),
  ('ex-leg-extensions', 'Leg Extensions', '{"legs"}', 'isolation', '{"machine"}', 3, '12-15', NULL),
  ('ex-leg-curls', 'Leg Curls', '{"legs"}', 'isolation', '{"machine"}', 3, '12-15', NULL),
  ('ex-calf-raises', 'Calf Raises', '{"legs"}', 'isolation', '{"bodyweight","dumbbell","machine"}', 3, '15-20', NULL),
  ('ex-leg-swings', 'Leg Swings', '{"legs","mobility"}', 'warmup', '{"bodyweight"}', NULL, NULL, '2 min'),
  ('ex-bicep-curls', 'Bicep Curls', '{"arms"}', 'isolation', '{"dumbbell","cable","band"}', 3, '10-15', NULL),
  ('ex-hammer-curls', 'Hammer Curls', '{"arms"}', 'isolation', '{"dumbbell"}', 3, '10-12', NULL),
  ('ex-tricep-pushdown', 'Tricep Pushdown', '{"arms"}', 'isolation', '{"cable","band"}', 3, '12-15', NULL),
  ('ex-overhead-tricep-ext', 'Overhead Tricep Extension', '{"arms"}', 'isolation', '{"dumbbell","cable"}', 3, '10-12', NULL),
  ('ex-tricep-dips', 'Tricep Dips', '{"arms"}', 'compound', '{"bodyweight"}', 3, '8-15', NULL),
  ('ex-plank', 'Plank', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, NULL, '45s'),
  ('ex-bicycle-crunches', 'Bicycle Crunches', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, '20', NULL),
  ('ex-leg-raises', 'Leg Raises', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, '15', NULL),
  ('ex-treadmill-sprints', 'Treadmill Sprints', '{"full_body"}', 'core_cardio', '{"machine"}', NULL, NULL, '20 min'),
  ('ex-burpees', 'Burpees', '{"full_body","core"}', 'core_cardio', '{"bodyweight"}', 3, '10', NULL),
  ('ex-jogging', 'Jogging', '{"legs"}', 'core_cardio', '{"bodyweight"}', NULL, NULL, '30 min'),
  ('ex-elliptical', 'Elliptical', '{"full_body"}', 'core_cardio', '{"machine"}', NULL, NULL, '30 min'),
  ('ex-dead-bugs', 'Dead Bugs', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, '12 each', NULL),
  ('ex-bird-dogs', 'Bird Dogs', '{"core","back"}', 'core_cardio', '{"bodyweight"}', 3, '10 each', NULL),
  ('ex-v-ups', 'V-Ups', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, '12', NULL),
  ('ex-side-plank', 'Side Plank', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, NULL, '30s each'),
  ('ex-hollow-hold', 'Hollow Body Hold', '{"core"}', 'core_cardio', '{"bodyweight"}', 3, NULL, '30s'),
  ('ex-mountain-climbers', 'Mountain Climbers', '{"core","full_body"}', 'core_cardio', '{"bodyweight"}', 3, '20', NULL),
  ('ex-high-knees', 'High Knees', '{"full_body","legs"}', 'core_cardio', '{"bodyweight"}', 3, NULL, '30s'),
  ('ex-jumping-jacks', 'Jumping Jacks', '{"full_body"}', 'core_cardio', '{"bodyweight"}', 3, NULL, '45s'),
  ('ex-yoga-flow', 'Yoga Flow', '{"mobility","full_body"}', 'core_cardio', '{"bodyweight"}', NULL, NULL, '15 min'),
  ('ex-foam-rolling', 'Foam Rolling', '{"mobility"}', 'core_cardio', '{"bodyweight"}', NULL, NULL, '10 min'),
  ('ex-deep-stretching', 'Deep Stretching', '{"mobility","full_body"}', 'core_cardio', '{"bodyweight"}', NULL, NULL, '10 min'),
  ('ex-light-walking', 'Light Walking', '{"mobility","legs"}', 'core_cardio', '{"bodyweight"}', NULL, NULL, '20 min'),
  ('ex-diamond-pushups', 'Diamond Push-ups', '{"chest","arms"}', 'compound', '{"bodyweight"}', 3, '10-15', NULL),
  ('ex-wide-pushups', 'Wide Push-ups', '{"chest"}', 'accessory', '{"bodyweight"}', 3, '12-15', NULL),
  ('ex-decline-pushups', 'Decline Push-ups', '{"chest","shoulders"}', 'compound', '{"bodyweight"}', 3, '10-12', NULL),
  ('ex-band-chest-fly', 'Band Chest Fly', '{"chest"}', 'isolation', '{"band"}', 3, '15-20', NULL),
  ('ex-band-pull-apart', 'Band Pull-Aparts', '{"back","shoulders"}', 'accessory', '{"band"}', 3, '15-20', NULL),
  ('ex-prone-y-raise', 'Prone Y-Raises', '{"back","shoulders"}', 'isolation', '{"bodyweight"}', 3, '12-15', NULL),
  ('ex-towel-rows', 'Towel Rows (Door)', '{"back"}', 'compound', '{"bodyweight"}', 3, '10-12', NULL),
  ('ex-band-rows', 'Band Rows', '{"back"}', 'accessory', '{"band"}', 3, '12-15', NULL),
  ('ex-band-lateral-raise', 'Band Lateral Raise', '{"shoulders"}', 'isolation', '{"band"}', 3, '15-20', NULL),
  ('ex-band-overhead-press', 'Band Overhead Press', '{"shoulders"}', 'compound', '{"band"}', 3, '12-15', NULL),
  ('ex-wall-handstand-hold', 'Wall Handstand Hold', '{"shoulders"}', 'compound', '{"bodyweight"}', 3, NULL, '20s'),
  ('ex-bulgarian-split-squat', 'Bulgarian Split Squat', '{"legs"}', 'compound', '{"bodyweight","dumbbell"}', 3, '10-12 each', NULL),
  ('ex-glute-bridge', 'Glute Bridge', '{"legs"}', 'accessory', '{"bodyweight"}', 3, '15-20', NULL),
  ('ex-wall-sit', 'Wall Sit', '{"legs"}', 'accessory', '{"bodyweight"}', 3, NULL, '45s'),
  ('ex-jump-squats', 'Jump Squats', '{"legs"}', 'compound', '{"bodyweight"}', 3, '12-15', NULL),
  ('ex-single-leg-dl', 'Single Leg Deadlift', '{"legs","core"}', 'accessory', '{"bodyweight","dumbbell"}', 3, '10 each', NULL),
  ('ex-step-ups', 'Step-Ups', '{"legs"}', 'accessory', '{"bodyweight","dumbbell"}', 3, '12 each', NULL),
  ('ex-sumo-squat', 'Sumo Squat', '{"legs"}', 'compound', '{"bodyweight","dumbbell"}', 3, '12-15', NULL),
  ('ex-band-curls', 'Band Bicep Curls', '{"arms"}', 'isolation', '{"band"}', 3, '15-20', NULL),
  ('ex-chair-dips', 'Chair Dips', '{"arms","chest"}', 'compound', '{"bodyweight"}', 3, '10-15', NULL),
  ('ex-band-tricep-ext', 'Band Tricep Extension', '{"arms"}', 'isolation', '{"band"}', 3, '15-20', NULL),
  ('ex-close-grip-pushups', 'Close-Grip Push-ups', '{"arms","chest"}', 'compound', '{"bodyweight"}', 3, '10-12', NULL)
ON CONFLICT (legacy_id) DO NOTHING;

-- 2. Seeds for exercise_details table
INSERT INTO public.exercise_details (id, name, primary_muscle, steps, form_cues)
VALUES
  ('ex-push-ups', 'Push-ups', 'Full Body', '{"Start in a high plank position with your hands slightly wider than shoulder-width apart.","Keep your core engaged, back flat, and neck neutral.","Lower your body until your chest nearly touches the floor.","Push back up to the starting position."}', '{"Keep elbows tucked at a 45-degree angle.","Squeeze your glutes and brace your core."}'),
  ('ex-db-bench-press', 'Dumbbell Bench Press', 'Chest', '{"Lie back on the bench holding dumbbells directly above your chest","Lower the dumbbells slowly until they are in line with your chest","Press the dumbbells back up to the starting position"}', '{"Keep your feet flat on the ground","Squeeze shoulders down and back"}'),
  ('ex-bb-bench-press', 'Barbell Bench Press', 'Full Body', '{"Lie on the bench with your eyes under the bar.","Grip the bar slightly wider than shoulder-width.","Unrack the bar and lower it to your mid-chest.","Press the bar back up in a slight arc toward your shoulders."}', '{"Drive through your heels.","Pull the bar apart to engage your lats."}'),
  ('ex-inc-db-press', 'Incline Dumbbell Press', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-mach-chest-press', 'Machine Chest Press', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-db-flyes', 'Dumbbell Flyes', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-cable-cross', 'Cable Crossovers', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-chest-press', 'Resistance Band Chest Press', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-arm-circles', 'Arm Circles', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-pull-ups', 'Pull-ups', 'Full Body', '{"Grab the pull-up bar with an overhand grip, slightly wider than shoulder-width.","Hang with your arms fully extended and core engaged.","Pull yourself up until your chin clears the bar.","Lower yourself slowly back to the starting position."}', '{"Drive your elbows down to the floor.","Keep your chest up."}'),
  ('ex-lat-pulldown', 'Lat Pulldown', 'Full Body', '{"Sit at the pulldown machine and adjust the knee pad.","Grip the bar wider than shoulder-width.","Pull the bar down toward your upper chest.","Slowly return the bar to the starting position."}', '{"Lean back slightly (about 10-15 degrees).","Squeeze your shoulder blades together at the bottom."}'),
  ('ex-bb-row', 'Barbell Row', 'Full Body', '{"Stand with feet shoulder-width apart, holding a barbell with an overhand grip.","Hinge at the hips, keeping your back straight and nearly parallel to the floor.","Row the barbell toward your lower chest/upper stomach.","Lower the bar under control."}', '{"Pull your elbows straight back.","Keep your chest up and lower back neutral."}'),
  ('ex-db-row', 'Dumbbell Row', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-seated-cable-row', 'Seated Cable Row', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-straight-arm-pulldown', 'Straight Arm Pulldown', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-superman-hold', 'Superman Hold', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-inverted-rows', 'Inverted Rows (Table)', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-cat-cow', 'Cat-Cow Stretch', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-overhead-press', 'Overhead Press', 'Shoulders', '{"Stand with feet shoulder-width apart, holding dumbbells at shoulder height","Press the weights straight up overhead until arms are extended","Lower under control back to shoulders"}', '{"Brace your core","Do not arch your lower back aggressively"}'),
  ('ex-pike-pushups', 'Pike Push-ups', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-lateral-raise', 'Lateral Raise', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-front-raise', 'Front Raise', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-face-pulls', 'Face Pulls', 'Full Body', '{"Attach a rope to a cable pulley set at upper-chest height.","Grip the rope from underneath and step back.","Pull the rope toward your face, letting your elbows flare high and wide.","Squeeze your upper back, then slowly return."}', '{"Imagine hitting a back double bicep pose.","Pull the center of the rope to your nose."}'),
  ('ex-mach-shoulder-press', 'Machine Shoulder Press', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-shoulder-dislocations', 'Shoulder Dislocations (Broomstick)', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-bb-squat', 'Barbell Squat', 'Quads / Glutes', '{"Unrack the barbell across your upper back, stepping back","Squat down by pushing hips back and bending knees","Drive through your heels to return to standing"}', '{"Chest up","Knees track over toes","Brace core"}'),
  ('ex-goblet-squat', 'Goblet Squat', 'Full Body', '{"Hold a dumbbell or kettlebell vertically against your chest.","Stand with feet slightly wider than shoulder-width.","Lower your hips down and back until your thighs are parallel to the floor.","Drive back to the starting position."}', '{"Keep your elbows tucked inside your knees at the bottom.","Keep the weight close to your body."}'),
  ('ex-bodyweight-squat', 'Bodyweight Squats', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-leg-press', 'Leg Press', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-rdl', 'Romanian Deadlift', 'Full Body', '{"Hold a barbell or dumbbells in front of your thighs.","Hinge at your hips, pushing them back while keeping your legs mostly straight (slight bend in the knee).","Lower the weight until you feel a deep stretch in your hamstrings.","Squeeze your glutes to return to a standing position."}', '{"Keep the bar/dumbbells dragging closely along your legs.","Maintain a flat, neutral back."}'),
  ('ex-lunges', 'Lunges', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-leg-extensions', 'Leg Extensions', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-leg-curls', 'Leg Curls', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-calf-raises', 'Calf Raises', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-leg-swings', 'Leg Swings', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-bicep-curls', 'Bicep Curls', 'Full Body', '{"Stand holding dumbbells with your palms facing forward.","Keep your upper arms stationary against your sides.","Curl the weights up toward your shoulders by flexing your elbows.","Lower the weights slowly."}', '{"Squeeze your biceps at the top.","Control the eccentric (lowering) phase."}'),
  ('ex-hammer-curls', 'Hammer Curls', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-tricep-pushdown', 'Tricep Pushdown', 'Full Body', '{"Attach a rope or straight bar to a high cable pulley.","Grip the attachment and tuck your elbows to your sides.","Push the attachment down until your arms are fully extended.","Return slowly to the starting position."}', '{"Keep your elbows pinned to your ribs.","Spread the rope apart at the bottom for an extra squeeze."}'),
  ('ex-overhead-tricep-ext', 'Overhead Tricep Extension', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-tricep-dips', 'Tricep Dips', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-plank', 'Plank', 'Full Body', '{"Start on your forearms and toes, with your elbows directly under your shoulders.","Keep your body in a straight line from your head to your heels.","Engage your core, glutes, and quads.","Hold the position for the specified duration."}', '{"Pull your belly button toward your spine.","Push the floor away with your forearms."}'),
  ('ex-bicycle-crunches', 'Bicycle Crunches', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-leg-raises', 'Leg Raises', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-treadmill-sprints', 'Treadmill Sprints', 'Full_body', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-burpees', 'Burpees', 'Full_body', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-jogging', 'Jogging', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-elliptical', 'Elliptical', 'Full_body', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-dead-bugs', 'Dead Bugs', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-bird-dogs', 'Bird Dogs', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-v-ups', 'V-Ups', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-side-plank', 'Side Plank', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-hollow-hold', 'Hollow Body Hold', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-mountain-climbers', 'Mountain Climbers', 'Core', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-high-knees', 'High Knees', 'Full_body', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-jumping-jacks', 'Jumping Jacks', 'Full_body', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-yoga-flow', 'Yoga Flow', 'Mobility', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-foam-rolling', 'Foam Rolling', 'Mobility', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-deep-stretching', 'Deep Stretching', 'Mobility', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-light-walking', 'Light Walking', 'Mobility', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-diamond-pushups', 'Diamond Push-ups', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-wide-pushups', 'Wide Push-ups', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-decline-pushups', 'Decline Push-ups', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-chest-fly', 'Band Chest Fly', 'Chest', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-pull-apart', 'Band Pull-Aparts', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-prone-y-raise', 'Prone Y-Raises', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-towel-rows', 'Towel Rows (Door)', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-rows', 'Band Rows', 'Back', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-lateral-raise', 'Band Lateral Raise', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-overhead-press', 'Band Overhead Press', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-wall-handstand-hold', 'Wall Handstand Hold', 'Shoulders', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-bulgarian-split-squat', 'Bulgarian Split Squat', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-glute-bridge', 'Glute Bridge', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-wall-sit', 'Wall Sit', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-jump-squats', 'Jump Squats', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-single-leg-dl', 'Single Leg Deadlift', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-step-ups', 'Step-Ups', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-sumo-squat', 'Sumo Squat', 'Legs', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-curls', 'Band Bicep Curls', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-chair-dips', 'Chair Dips', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-band-tricep-ext', 'Band Tricep Extension', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}'),
  ('ex-close-grip-pushups', 'Close-Grip Push-ups', 'Arms', '{"Consult your coach for proper form.","Maintain steady breathing.","Control the movement."}', '{"Focus on the target muscle.","Keep your core engaged."}')
ON CONFLICT (id) DO NOTHING;
